const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jitlog', {
  getTodayTasks:      ()            => ipcRenderer.invoke('get-today-tasks'),
  getAllTasks:         ()            => ipcRenderer.invoke('get-all-tasks'),
  getTask:            (id)          => ipcRenderer.invoke('get-task', id),
  getElapsed:         (task)        => ipcRenderer.invoke('get-elapsed', task),
  getSlots:           ()            => ipcRenderer.invoke('get-slots'),
  createTask:         (name, client)        => ipcRenderer.invoke('create-task', name, client),
  createTaskInSlot:   (name, slot, client)  => ipcRenderer.invoke('create-task-in-slot', name, slot, client),
  reviveTask:         (id)                  => ipcRenderer.invoke('revive-task', id),
  getSettings:        ()                    => ipcRenderer.invoke('get-settings'),
  saveSettings:       (s)                   => ipcRenderer.invoke('save-settings', s),
  getThemes:          ()                    => ipcRenderer.invoke('get-themes'),
  saveCustomTheme:    (name, vars)          => ipcRenderer.invoke('save-custom-theme', name, vars),
  deleteCustomTheme:  (name)               => ipcRenderer.invoke('delete-custom-theme', name),
  openSettingsFile:   ()                    => ipcRenderer.send('open-settings-file'),
  reloadSettings:     ()                    => ipcRenderer.send('reload-settings'),
  onApplyTheme:       (cb)                  => ipcRenderer.on('apply-theme', (_, vars) => cb(vars)),
  startTask:          (id)          => ipcRenderer.invoke('start-task', id),
  pauseTask:          (id)          => ipcRenderer.invoke('pause-task', id),
  archiveTask:        (id)          => ipcRenderer.invoke('archive-task', id),
  updateNotes:        (id, n)       => ipcRenderer.invoke('update-notes', id, n),
  updateLink:         (id, url)     => ipcRenderer.invoke('update-link', id, url),
  updateClient:       (id, client)  => ipcRenderer.invoke('update-client', id, client),
  saveImage:          (buf)         => ipcRenderer.invoke('save-image', buf),
  addImage:           (id, p)       => ipcRenderer.invoke('add-image', id, p),
  copyTaskContent:    (id)          => ipcRenderer.invoke('copy-task-content', id),
  deleteTask:         (id)          => ipcRenderer.invoke('delete-task', id),
  swapTaskSlots:      (id1, id2)    => ipcRenderer.invoke('swap-task-slots', id1, id2),
  sortTasksByClient:  ()            => ipcRenderer.invoke('sort-tasks-by-client'),
  updateTaskName:     (id, name)    => ipcRenderer.invoke('update-task-name', id, name),
  archiveAllTasks:    ()            => ipcRenderer.invoke('archive-all-tasks'),
  copyDaySummary:     ()            => ipcRenderer.invoke('copy-day-summary'),
  quitApp:            ()            => ipcRenderer.send('quit-app'),
  closeWindow:        ()            => ipcRenderer.send('close-window'),
  openGrid:           ()            => ipcRenderer.send('open-grid'),
  closeGrid:          ()            => ipcRenderer.send('close-grid'),
  cycleGridDisplay:   ()            => ipcRenderer.send('cycle-grid-display'),
  refreshPanel:       ()            => ipcRenderer.send('refresh-panel'),
  resizePanel:        (h)           => ipcRenderer.send('resize-panel', h),
  // tray renderer
  onRenderTray:       (cb)          => ipcRenderer.on('render-tray', (_, d) => cb(d)),
  trayImageReady:     (url, isTemplate) => ipcRenderer.send('tray-image', url, isTemplate),
  // panel events
  onTick:             (cb)          => ipcRenderer.on('tick',           (_) => cb()),
  onRefresh:          (cb)          => ipcRenderer.on('refresh',        (_) => cb()),
  onFocusNewTask:     (cb)          => ipcRenderer.on('focus-new-task', (_) => cb()),
  onShowDocs:         (cb)          => ipcRenderer.on('show-docs',   (_, id) => cb(id)),
  onShowHistory:      (cb)          => ipcRenderer.on('show-history',   (_) => cb()),
});
